import { ContentType, IBiliCard } from './../components/card/BiliCard'

export const cardList: IBiliCard[] = [
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/510',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/530',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/570',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/590',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/500',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/501',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/538',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/520',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/521',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/525',
    },
    {
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/527',
    },
]
