import { ContentType, IBiliCard } from './../components/card/BiliCard'

export const cardList: IBiliCard[] = [
    {
        id: 1,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/510',
    },
    {
        id: 2,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/530',
    },
    {
        id: 3,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/570',
    },
    {
        id: 4,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/590',
    },
    {
        id: 5,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/500',
    },
    {
        id: 6,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/501',
    },
    {
        id: 7,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/538',
    },
    {
        id: 8,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/520',
    },
    {
        id: 9,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/521',
    },
    {
        id: 10,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/525',
    },
    {
        id: 11,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/527',
    },
    {
        id: 12,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/501',
    },
    {
        id: 13,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/538',
    },
    {
        id: 14,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/520',
    },
    {
        id: 15,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/521',
    },
]
