import { ContentType, IBiliCard } from './../components/card/BiliCard'

export const carouselList = [
    {
        id: 1,
        url: 'https://i.pravatar.cc/501',
        title: '下班后，这才是我的生活111',
    },
    {
        id: 2,
        url: 'https://i.pravatar.cc/502',
        title: '下班后，这才是我的生活222',
    },
    {
        id: 3,
        url: 'https://i.pravatar.cc/503',
        title: '下班后，这才是我的生活333',
    },
    {
        id: 4,
        url: 'https://i.pravatar.cc/504',
        title: '下班后，这才是我的生活444',
    },
    {
        id: 5,
        url: 'https://i.pravatar.cc/505',
        title: '下班后，这才是我的生活555',
    },
    {
        id: 6,
        url: 'https://i.pravatar.cc/506',
        title: '下班后，这才是我的生活666',
    },
    {
        id: 7,
        url: 'https://i.pravatar.cc/507',
        title: '下班后，这才是我的生活777',
    },
    {
        id: 8,
        url: 'https://i.pravatar.cc/508',
        title: '下班后，这才是我的生活888',
    },
    {
        id: 9,
        url: 'https://i.pravatar.cc/509',
        title: '下班后，这才是我的生活999',
    },
]

export const cardList: IBiliCard[] = [
    {
        id: 1,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/510',
    },
    {
        id: 2,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/530',
    },
    {
        id: 3,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/570',
    },
    {
        id: 4,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/590',
    },
    {
        id: 5,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/500',
    },
    {
        id: 6,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/501',
    },
    {
        id: 7,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/538',
    },
    {
        id: 8,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/520',
    },
    {
        id: 9,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/521',
    },
    {
        id: 10,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/525',
    },
    {
        id: 11,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/527',
    },
    {
        id: 12,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/501',
    },
    {
        id: 13,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/538',
    },
    {
        id: 14,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.UP,
        img: 'https://i.pravatar.cc/520',
    },
    {
        id: 15,
        title: '世界杯决赛上演帽子戏法，姆巴佩赢得了这个世界的尊重吗',
        author: '巴黎姆学院',
        date: '12-5',
        play: '31万',
        comment: 955,
        time: '05:32',
        contentType: ContentType.SHOW,
        img: 'https://i.pravatar.cc/521',
    },
]
